'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="Direcciones")>  _
Partial Public Class DataClassesDireccionesDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  Partial Private Sub InsertDireccione(instance As Direccione)
    End Sub
  Partial Private Sub UpdateDireccione(instance As Direccione)
    End Sub
  Partial Private Sub DeleteDireccione(instance As Direccione)
    End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.GPSDataOSM.My.MySettings.Default.DireccionesConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property Direcciones() As System.Data.Linq.Table(Of Direccione)
		Get
			Return Me.GetTable(Of Direccione)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.Direcciones")>  _
Partial Public Class Direccione
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _dir_codigo As Integer
	
	Private _dir_latitud As String
	
	Private _dir_longitud As String
	
	Private _dir_nombre_via As String
	
	Private _dir_localidad As String
	
	Private _dir_provinica As String
	
	Private _dir_tipo_via As Integer
	
	Private _dir_origen As String
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub Ondir_codigoChanging(value As Integer)
    End Sub
    Partial Private Sub Ondir_codigoChanged()
    End Sub
    Partial Private Sub Ondir_latitudChanging(value As String)
    End Sub
    Partial Private Sub Ondir_latitudChanged()
    End Sub
    Partial Private Sub Ondir_longitudChanging(value As String)
    End Sub
    Partial Private Sub Ondir_longitudChanged()
    End Sub
    Partial Private Sub Ondir_nombre_viaChanging(value As String)
    End Sub
    Partial Private Sub Ondir_nombre_viaChanged()
    End Sub
    Partial Private Sub Ondir_localidadChanging(value As String)
    End Sub
    Partial Private Sub Ondir_localidadChanged()
    End Sub
    Partial Private Sub Ondir_provinicaChanging(value As String)
    End Sub
    Partial Private Sub Ondir_provinicaChanged()
    End Sub
    Partial Private Sub Ondir_tipo_viaChanging(value As Integer)
    End Sub
    Partial Private Sub Ondir_tipo_viaChanged()
    End Sub
    Partial Private Sub Ondir_origenChanging(value As String)
    End Sub
    Partial Private Sub Ondir_origenChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_dir_codigo", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property dir_codigo() As Integer
		Get
			Return Me._dir_codigo
		End Get
		Set
			If ((Me._dir_codigo = value)  _
						= false) Then
				Me.Ondir_codigoChanging(value)
				Me.SendPropertyChanging
				Me._dir_codigo = value
				Me.SendPropertyChanged("dir_codigo")
				Me.Ondir_codigoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_dir_latitud", DbType:="VarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property dir_latitud() As String
		Get
			Return Me._dir_latitud
		End Get
		Set
			If (String.Equals(Me._dir_latitud, value) = false) Then
				Me.Ondir_latitudChanging(value)
				Me.SendPropertyChanging
				Me._dir_latitud = value
				Me.SendPropertyChanged("dir_latitud")
				Me.Ondir_latitudChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_dir_longitud", DbType:="VarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property dir_longitud() As String
		Get
			Return Me._dir_longitud
		End Get
		Set
			If (String.Equals(Me._dir_longitud, value) = false) Then
				Me.Ondir_longitudChanging(value)
				Me.SendPropertyChanging
				Me._dir_longitud = value
				Me.SendPropertyChanged("dir_longitud")
				Me.Ondir_longitudChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_dir_nombre_via", DbType:="VarChar(100) NOT NULL", CanBeNull:=false)>  _
	Public Property dir_nombre_via() As String
		Get
			Return Me._dir_nombre_via
		End Get
		Set
			If (String.Equals(Me._dir_nombre_via, value) = false) Then
				Me.Ondir_nombre_viaChanging(value)
				Me.SendPropertyChanging
				Me._dir_nombre_via = value
				Me.SendPropertyChanged("dir_nombre_via")
				Me.Ondir_nombre_viaChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_dir_localidad", DbType:="VarChar(100) NOT NULL", CanBeNull:=false)>  _
	Public Property dir_localidad() As String
		Get
			Return Me._dir_localidad
		End Get
		Set
			If (String.Equals(Me._dir_localidad, value) = false) Then
				Me.Ondir_localidadChanging(value)
				Me.SendPropertyChanging
				Me._dir_localidad = value
				Me.SendPropertyChanged("dir_localidad")
				Me.Ondir_localidadChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_dir_provinica", DbType:="VarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property dir_provinica() As String
		Get
			Return Me._dir_provinica
		End Get
		Set
			If (String.Equals(Me._dir_provinica, value) = false) Then
				Me.Ondir_provinicaChanging(value)
				Me.SendPropertyChanging
				Me._dir_provinica = value
				Me.SendPropertyChanged("dir_provinica")
				Me.Ondir_provinicaChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_dir_tipo_via", DbType:="Int NOT NULL")>  _
	Public Property dir_tipo_via() As Integer
		Get
			Return Me._dir_tipo_via
		End Get
		Set
			If ((Me._dir_tipo_via = value)  _
						= false) Then
				Me.Ondir_tipo_viaChanging(value)
				Me.SendPropertyChanging
				Me._dir_tipo_via = value
				Me.SendPropertyChanged("dir_tipo_via")
				Me.Ondir_tipo_viaChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_dir_origen", DbType:="VarChar(50)")>  _
	Public Property dir_origen() As String
		Get
			Return Me._dir_origen
		End Get
		Set
			If (String.Equals(Me._dir_origen, value) = false) Then
				Me.Ondir_origenChanging(value)
				Me.SendPropertyChanging
				Me._dir_origen = value
				Me.SendPropertyChanged("dir_origen")
				Me.Ondir_origenChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class
